dist: bionic
services:
  - xvfb
language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - '3.7'
matrix:
  fast_finish: true
before_install:
  - firefox -v
  - virtualenv .
  - bin/pip install --upgrade -r requirements.txt
install:
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
  - bin/buildout -c develop.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -c develop.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C bin
  - export PATH=$(pwd)/bin:$PATH

script:
  - bin/code-analysis
  - bin/test
  - export ROBOTSUITE_PREFIX=ONLYROBOT && bin/test -t ONLYROBOT --all

after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
